Onboarding carousel more adjustments
cesko-digital/loono pull request #10
Opened 2021-08-02 09:00 UTC by mzdm

Toto je based na #8, ale udělal jsem separatni PR ať v tom není zmatek a v případě větších bugů se to může prostě revertnout. Zatím jen draft, protože to zasahuje i do fungování pluginu (video_player), na iPhonu se to může chovat asi jinak (jestli může někdo prosím otestovat).

Toto adressuje 2 issues z https://github.com/cesko-digital/loono/pull/8#issuecomment-890519213:
- 1\. commit fixuje případ, kdy indikátor běžel i když nebylo načetlé video
- 2\. commit přidává možnost stopnutí story

Místy mi to příjde trošku "oheckované", někde jsem přidal koment proč tam je tam ten kod atd. např. bez toho 750s delaye u toho videa v `didUpdateWidget` to při swipnutí přehraje na chvíili zvuk znova :/

2021-08-03 07:16 UTC, killalad commented on lib/ui/widgets/video_player.dart
> +          await Future.delayed(const Duration(milliseconds: 750));
tohle je za me hroozne nepekny, neslo by to aspon vyresit nejak pres to ze treba pri zmene stranky tam poslem paused na true nebo tak? Tyhle random delaye jsou vzdycky cesta do pekla a kazdy device je jiny nekde je treba vic nekde min

2021-08-03 07:42 UTC, mzdm commented on lib/ui/widgets/video_player.dart
> +          await Future.delayed(const Duration(milliseconds: 750));
true, zkusím to nějak pořešit

2021-08-03 10:34 UTC, mzdm commented
jako takhle to funguje, jen to má 2 issues:
1. který spíš souvisí s pluginem, že mu trvá tak dlouho než disposne (když swipne na další screen, tak asi 0,5s ještě zvuk hraje) - ale při tapnutí to nedělá 🤔
2. když rychle swipne doprava a zpět na video, tak se sekne. Pokud chápu dobře, tak ten screen ještě "žije" takže `initState` se nevolá a volá se `didUpdateWidget`, jenže když tam volám tu funkci `widget.onLoaded?.call();`, tak to crashuje (když tam je ten delay, tak ne ale to zas není věrohodný jak si psal). Možná nějak přes to PageVIew jestli jde detekovat že se neswiplo úplně, tak pak nevolat `pauseStory`, ale tu moc nevím 🤷‍♂️

viz video co myslím
https://user-images.githubusercontent.com/67197047/128001164-09a0d2f5-7b2a-4e84-a306-9e7dbd8601b2.mp4

2021-08-04 08:43 UTC, mzdm commented
Už by to mělo být snad fixed (to pauzovani), testováno na Androidu

2021-08-06 17:46 UTC, mzdm commented
Design carouselu se dnes zase ještě upravoval a teď je tam jen 1 story s videem, takže ten sound delay při swipnutí se nemusí řešit.

2021-08-15 18:07 UTC, killalad requested changes

2021-08-15 18:07 UTC, killalad commented on lib/ui/widgets/video_player.dart
> +      // floatingActionButton: FloatingActionButton(
uz muzeme odstranit ne?

2021-08-15 18:25 UTC, mzdm commented on lib/ui/widgets/video_player.dart
> +      // floatingActionButton: FloatingActionButton(
smazano, i ta testovaci délka u druhého carouselu

2021-08-16 17:25 UTC, killalad approved these changes

2021-08-16 17:25 UTC, merged