after_deletation
cesko-digital/loono pull request #109
Opened 2022-02-12 07:28 UTC by mattpake

https://cesko-digital.atlassian.net/browse/LOON-238
Krok 5

2022-02-13 12:29 UTC, killalad submitted a review, later dismissed

2022-02-13 12:29 UTC, killalad commented on lib/ui/screens/settings/delete_account.dart
> +                                await registry.get<UserRepository>().deleteAccount();
pockat nejdriv by mel byt ten delete a az potom pod toho jestli rekl true/false, tak redirectovat a dat success snackbar, ale kdyz false tak zas dat error snackbar a neredirectovat

2022-02-13 15:43 UTC, killalad commented
ceka na Radek protoze ve firebase se nemaze a DB neni otestovana

2022-02-21 19:55 UTC, mattpake commented
Preverene v DB aj FB , maže to account správne. Prosím o schválenie.

2022-02-21 20:18 UTC, mzdm requested changes
`pubspec.lock` by neměl mít nějaké změny, žádné deps se neupravovaly. Můžeš to prosím rechecknout? Codemagic může s tím mít při buildu problém. Nejlíp udělej `flutter clean` a spusť appku. Přegeneruje se to a pak zkus pushnout změny.

2022-02-21 21:47 UTC, MartinMacek reviewed
ještě nějaké strings pls

2022-02-21 21:47 UTC, MartinMacek commented on lib/l10n/intl_cs.arb
> +  "settings_after_deletion_deleted": "Tvůj účet sme smazali",
tady vidím typo "sme" -> "jsme"

2022-02-21 21:47 UTC, MartinMacek commented on lib/l10n/intl_cs.arb
> +  "settings_after_deletion_what_we_can_do": "Co můžeme udělat pro to, aby ses do aplikace vrátil/a?",
to pohlaví už používáme v appce tak by to bylo fajn předělat podle správného typu "vrátil/a?"

2022-02-21 21:50 UTC, MartinMacek commented on lib/l10n/intl_cs.arb
> +  "settings_after_deletion_give_as_feetback": "Budeme moc rádi, když nám napíšeš, co ti v aplikaci nesedělo. Chceme ji pořád zlepšovat a taky si přejeme, aby ses mohl/a vrátit.",
a "mohl/a"

2022-02-22 19:11 UTC, mattpake commented on lib/l10n/intl_cs.arb
> +  "settings_after_deletion_give_as_feetback": "Budeme moc rádi, když nám napíšeš, co ti v aplikaci nesedělo. Chceme ji pořád zlepšovat a taky si přejeme, aby ses mohl/a vrátit.",
Uz to rozoznava podla sex

2022-02-22 19:13 UTC, mattpake commented
> `pubspec.lock` by neměl mít nějaké změny, žádné deps se neupravovaly. Můžeš to prosím rechecknout? Codemagic může s tím mít při buildu problém. Nejlíp udělej `flutter clean` a spusť appku. Přegeneruje se to a pak zkus pushnout změny.

Pregenerovl som to a pushol zmeny. Ak to takto neni pohode jedine to môžem revertnúť a zmeniť ale do toho sa mi nechce to bolo v mergy tak bude mega konfliktov.

2022-02-22 22:54 UTC, mzdm commented on lib/ui/screens/settings/after_deletion.dart
> +
ad) pubspec - teď by to mělo být ok, díky. předtím se tam měnila verze loono-api a mazala 1 dependency

k tomu pohlaví tady ještě: protože v předchozím screenu mažeš db a účet, tak toto vždycky fallbackne na muže.
solution: v předchozím screenu uložit pohlaví do proměnné a to poslat na tuto screenu přes parametr

2022-02-23 10:54 UTC, mattpake commented on lib/ui/screens/settings/after_deletion.dart
> +
hodene do parametru, otestovane funguje to

2022-02-23 11:13 UTC, mzdm approved these changes
lgtm, potvrzuju že se data mažou z db i Firebase

2022-02-23 11:15 UTC, merged