LOON-60 Update Gender screen
cesko-digital/loono pull request #11
Opened 2021-08-02 18:04 UTC by mzdm

- screen je hotov už od někoho z hackdaye, toto jen update barev podle Figmy a přidání toho BottomModalView dialogu u other genderu

2021-08-03 10:34 UTC, killalad requested changes
Postyluj prosim jeste ty velikosti pisem, paddingu, sirek a tak u tech gender tlacitek (na iphone 12 to takhle preteka), at kdyz uz to pretece tak at je to nejak na stred a zaroven at to preteka fakt jen na malych devices))

2021-08-03 13:18 UTC, mzdm commented
> Postyluj prosim jeste ty velikosti pisem, paddingu, sirek a tak u tech gender tlacitek (na iphone 12 to takhle preteka), at kdyz uz to pretece tak at je to nejak na stred a zaroven at to preteka fakt jen na malych devices))

done, nevím jestli to bylo myšleno takhle.. testovani tý responzivnosti je torchu těžší, já osobně pouštím Windows desktop appku tam se dá krásně měnit velikost okna :D

2021-08-09 19:48 UTC, ryzizub commented
Je to lepší, jen jsem si všiml, že ve figmě ten bottom modal nemá zašedlé pozadí ale tady má. To bych ještě zjistil 
![Snímek obrazovky 2021-08-09 v 21 46 30](https://user-images.githubusercontent.com/32575328/128765370-0c1a8044-3c86-4bd3-ada3-7bb42a965eb1.png)
![Snímek obrazovky 2021-08-09 v 21 46 40](https://user-images.githubusercontent.com/32575328/128765377-bee6a220-a620-45b4-99b7-a58114c061e6.png)

2021-08-10 08:31 UTC, mzdm commented
> Je to lepší, jen jsem si všiml, že ve figmě ten bottom modal nemá zašedlé pozadí ale tady má. To bych ještě zjistil
> ![Snímek obrazovky 2021-08-09 v 21 46 30](https://user-images.githubusercontent.com/32575328/128765370-0c1a8044-3c86-4bd3-ada3-7bb42a965eb1.png)
> ![Snímek obrazovky 2021-08-09 v 21 46 40](https://user-images.githubusercontent.com/32575328/128765377-bee6a220-a620-45b4-99b7-a58114c061e6.png)

nice catch, díky!
pak se Otakara zeptám, teď je na dovolený myslím

2021-08-12 12:19 UTC, ryzizub commented
@mzdm ještě mě napadá, že ta SafeArea na iOS posouvá ten dialog dost nahoru (protože dole je ten gesture indicator), timpádem je tam do očí bijící mezera. Ještě bych zkusil tohle upravit

2021-08-12 12:56 UTC, mzdm commented
> @mzdm ještě mě napadá, že ta SafeArea na iOS posouvá ten dialog dost nahoru (protože dole je ten gesture indicator), timpádem je tam do očí bijící mezera. Ještě bych zkusil tohle upravit

teď jen ujišťuju - je tam nějaká černá mezera mezi gesture detector a tím BottomModalSheet nebo myslíš tu béžovou pod textem ? upravil jsem spacing tý béžový mezery na větších screenech (na 4,7" screenu ten text byl úplně dole).

2021-08-17 07:20 UTC, mzdm commented
Dnes ráno mi Otakar psal, že by to nakonec ztmavené být nemělo.

2021-08-17 19:13 UTC, killalad approved these changes
lgtm, link funguje i na ios, ale todo zatim nechme uplne si nejsem jisty jestli je to potreba (https afaik funguje vzdycky a http bych nechtel referencovat tak i tak)

2021-08-17 19:13 UTC, merged