Loon 53/115
cesko-digital/loono pull request #14
Opened 2021-08-03 17:04 UTC by VojtechOboril

2021-08-06 17:55 UTC, mzdm commented
Ahoj, máš tam nějaké konflikty

2021-08-09 08:11 UTC, smolikja commented
Ahoj @VojtechOboril, mohl bys prosim udelat screenu prepouzivatelnou pro ostatni doktory a mozna i do budoucna? Podobne to mam ve sve branch, kterou mam jeste rozdelanou pro otazky ohledne doktoru. Pokud bys nechapal, co tim myslim, nebo si myslel, ze je to hloupost, dej mi prosim vedet:)

https://github.com/smolikja/loono/tree/feature/universal-doctor

2021-08-12 12:26 UTC, smolikja commented on lib/ui/screens/onboarding/doctors/gynecology.dart
>  class OnboardingGynecologyScreen extends StatelessWidget {
Bojim se ale, ze se jedna o zasah do me branch jenz jsem zminoval vyse. Tam je to v podstate hotove, cekam na poprani se s konflikty a hodim to na PR. To bych mohl hodit do zitra bez ohledu na jine tasky.

2021-08-16 17:27 UTC, killalad requested changes
lgtm jen prosim jeste ty konflitky

2021-08-17 19:31 UTC, killalad requested changes
Ahoj, prosimte dost se toho v masteru zmenilo a ty routy ti ted nefunguji, neni treba zadna `/award` a zadoven ty skipy by meli preskocit daneho doktora ale pripadne jit na dalsiho (pokud je to posledni jako je gynekologie tak pak na tu AwardScreen) ale jinak ty normalni buttony by ho meli poslat na tu date picker screenu.

Navic mame ted dve v podstate stejne obrazovky, tu achievement a tu award tak to prosim rovnou nejak sjednot. Diky!

2021-08-19 17:29 UTC, killalad approved these changes
lgtm

2021-08-19 17:29 UTC, merged