LOON-116 Gynecology date screen
cesko-digital/loono pull request #15
Opened 2021-08-07 10:33 UTC by phiviet01

2021-08-09 08:10 UTC, smolikja commented
Ahoj @phiviet01, mohl bys prosim udelat screenu prepouzivatelnou pro ostatni doktory a mozna i do budoucna? Podobne to mam ve sve branch, kterou mam jeste rozdelanou pro otazky ohledne doktoru. Pokud bys nechapal, co tim myslim, nebo si myslel, ze je to hloupost, dej mi prosim vedet:)

https://github.com/smolikja/loono/tree/feature/universal-doctor

2021-08-09 19:20 UTC, ryzizub commented
Souhlasím se @smolikja, bylo by dobré udělat takové obecné screeny, které se určitě budou hodit znovu, znovupoužitelné

2021-08-10 09:32 UTC, phiviet01 commented
Ještě sjednotím screeny, kde se budou používat datepicker.

2021-08-14 16:21 UTC, phiviet01 commented
@smolikja @ryzizub Updatnuto.

2021-08-16 17:28 UTC, killalad requested changes
lgtm jen konflikty

2021-08-17 07:09 UTC, phiviet01 commented
@killalad v rámci PR jsem přidal rovnou i https://cesko-digital.atlassian.net/browse/LOON-113 (Dentist date screen)

2021-08-17 07:14 UTC, smolikja commented
> @killalad v rámci PR jsem přidal rovnou i https://cesko-digital.atlassian.net/browse/LOON-113 (Dentist date screen)

prisoupl bys prosim i pro praktika, at je to komplet? :) ten screen nema ani issue ja jire

2021-08-17 07:36 UTC, phiviet01 commented
@smolikja @killalad Díky za postřeh. Udělal jsem :)

2021-08-17 07:43 UTC, killalad approved these changes
lgtm

2021-08-17 07:43 UTC, merged