Feature/universal doctor
cesko-digital/loono pull request #17
Opened 2021-08-15 11:35 UTC by smolikja

Ahoj, jedna se o reusable screenu pro onboarding otazky ohledne doktoru a reusable widget pro otazku ohledne doktoru.

2021-08-16 08:07 UTC, ryzizub commented on lib/l10n/intl_cs.arb
> +  "universal_dr_dentist_question_header": "ZUBAŘE?",
Prosím lowercase a až na straně použítí to dát do uppercase

2021-08-16 08:07 UTC, ryzizub commented
Je potřeba vyřešit konflikty

2021-08-16 15:25 UTC, smolikja commented
> 
> 
> Je potřeba vyřešit konflikty

done

2021-08-16 16:46 UTC, smolikja commented on lib/l10n/intl_cs.arb
> +  "universal_dr_dentist_question_header": "ZUBAŘE?",
done

2021-08-16 17:37 UTC, killalad requested changes
je tady navic PRko ktery resi stejny issue tak uplne moc nevim co ted s tim kdyz je to udelane 2x a jinak @ryzizub

2021-08-16 17:37 UTC, killalad commented on lib/main.dart
> +class Loono extends StatelessWidget {
tohle sem nepatri ta loono classa je jen v `Loono.dart`

2021-08-16 17:55 UTC, smolikja commented on lib/main.dart
> +class Loono extends StatelessWidget {
done

2021-08-17 19:19 UTC, killalad commented
jak jsme se dohodli, udela se teda nakonec nove PR nad tim @VojtechOboril kodem

2021-08-17 19:19 UTC, closed without merging