display_badges
cesko-digital/loono pull request #174
Opened 2022-03-13 20:47 UTC by mattpake

2022-03-14 16:38 UTC, mattpake commented
https://cesko-digital.atlassian.net/browse/LOON-401

2022-03-14 21:45 UTC, MartinMacek commented on lib/ui/screens/prevention/examination_detail/examination_badges.dart
> +  bool _showGreenBadge(Badge? data, int index) {
taková drobnost. šlo by prosím přesunout všechno co je tady pod `build` metodou nahoru nad ni? čistě ze zvyku to tady nikdo neočekává, tak ať to zbytečně nemate

2022-03-14 21:50 UTC, MartinMacek commented on lib/l10n/intl_cs.arb
> +  "examination_detail_rewards_get_badge_1": "Za dokončenou preventivní prohlídku získaš",
typo ve slově "získáš"

2022-03-14 21:50 UTC, MartinMacek commented on lib/ui/screens/prevention/examination_detail/examination_badges.dart
> +          future: _currentBadge(),
když tady používáš Future builder, můžeš volat UserRepository přímo tady a nemusíš ho passovat z examination_detailu. Navíc se tak můžeš zbavit mezikroku `_currentBadge`. Zjednodušit to jde třeba takhle:
<img width="486" alt="Screenshot 2022-03-14 at 22 42 05" src="https://user-images.githubusercontent.com/19749268/158266169-1273616c-4320-40cb-8425-3da904f7d21e.png">

2022-03-14 21:51 UTC, MartinMacek commented on lib/ui/screens/prevention/examination_detail/examination_badges.dart
> +        return 'čelenka';
tady asi raději "čelenku"?

2022-03-15 20:33 UTC, MartinMacek requested changes

2022-03-15 20:33 UTC, MartinMacek commented on lib/ui/screens/prevention/examination_detail/examination_badges.dart
> +    }
díky za přesunutí nahoru. Poslední výtka je, že teď jsou metody `_showPointsText`, `_showRedBadge` a `_showGreenBadge` uvnitř build metody, takže se znovu iniciují při každém rebuildu. Mohl bys je ještě pls hodit ven nad build? Na stejnou úroveň jako třeba `badgeCZ`. Zbytek už vypadá dobře.

2022-03-15 20:33 UTC, MartinMacek commented on lib/ui/screens/prevention/examination_detail/examination_badges.dart
> +          // future: _currentBadge(),
ještě tady vidím  nepotřebný koment :)

2022-03-16 08:27 UTC, MartinMacek approved these changes
lgtm. Dík za úpravy

2022-03-16 08:27 UTC, merged