edit last visited month
cesko-digital/loono pull request #187
Opened 2022-03-22 13:55 UTC by ulcdenis

https://cesko-digital.atlassian.net/browse/LOON-538

2022-03-23 13:07 UTC, mzdm requested changes
Ahoj, v tomto ta chyba není

to je helper funkce pro získání enumu z pořadového čísla měsíce, a jelikož enumy se indexují od 0, tak se tam odečítá ta 1 (první měsíc, leden = 0). Sice to zrovna fixne tento případ, ale naopak to posune pak datum narození

koukl jsem se na to, a problém ej v tom že datum poslední prohlídky se musí posílat v UTC timu, a tím pádem dojde ke shiftu (když zadám že jsem byl v březnu 2021, tak v UTC se pošle poslední den v únoru 2021 22:00). Vypadá to že BE ten UTC time nehandluje a bere ho jako lokální.

V `lib/ui/screens/onboarding/fallback_account/email.dart` se musí upravit posílání na "fake" utc:
```diff
--- a/lib/ui/screens/onboarding/fallback_account/email.dart
+++ b/lib/ui/screens/onboarding/fallback_account/email.dart
@@ -97,6 +97,21 @@ class EmailScreen extends StatelessWidget {
       dentist,
     ].whereType<ExaminationQuestionnaire>();

+    DateTime? getFakeUtcDate(DateTime? dateTime) {
+      DateTime? utcNewDate;
+      if (dateTime != null) {
+        utcNewDate = DateTime.utc(
+          dateTime.year,
+          dateTime.month,
+          dateTime.day,
+          dateTime.hour,
+          dateTime.minute,
+          dateTime.second,
+        );
+      }
+      return utcNewDate;
+    }
+
     return _apiService.onboardUser(
       sex: user.sex!,
       birthdate: user.dateOfBirth!,
@@ -106,7 +121,7 @@ class EmailScreen extends StatelessWidget {
             ExaminationRecord((b) {
               b
                 ..status = questionnaire.status
-                ..date = questionnaire.date?.toUtc()
+                ..date = getFakeUtcDate(questionnaire.date)
                 ..firstExam = true
                 ..type = questionnaire.type;
             })

```

a v examination_detail.dart všude volat `.toLocal()` kde ještě není, např.:
```diff
+++ b/lib/ui/screens/prevention/examination_detail/examination_detail.dart
@@ -76,7 +76,7 @@ class ExaminationDetail extends StatelessWidget {
   @override
   Widget build(BuildContext context) {
     final l10n = context.l10n;
-    final lastVisitDateWithoutDay = categorizedExamination.examination.lastConfirmedDate;
+    final lastVisitDateWithoutDay = categorizedExamination.examination.lastConfirmedDate?.toLocal();

     final lastVisit = lastVisitDateWithoutDay != null
         ? DateFormat.yMMMM('cs-CZ').format(

```

2022-03-26 18:43 UTC, mzdm commented
@ulcdenis jestli máš nějaký block, dej vědět tu / mně na Slacku ať toto můžem vyřešit :)

2022-03-31 16:34 UTC, MartinMacek commented
Zkoušel jsem a zdá se že funguje. Je to jak říká Matěj, fake utc je tam kvůli open api a serveru je jedno jaký date pošleme, dokud budeme konzistentní.

2022-03-31 17:52 UTC, mzdm approved these changes
Dořešeno přes Slack, ještě se všimlo nějakých nesrovnalostí s DateTimem u progressbarů

2022-03-31 17:57 UTC, merged