feat(ci): firebase test lab - frontend tests
cesko-digital/loono pull request #205
Opened 2022-04-02 20:14 UTC by mzdm

- Přesunutí integračních frontend testů do Firebase Test Lab
  -  jsou více věrohodné (skoro žádná flakiness), dokáží běžet na fyzických zařízení oproti Github Actions
  - nahrává se u nich automaticky video a ukládají logy (na 90 dnů)
  - je tam limit 5 runů na fyzických zař. den a 10 runů na virtuální zařízení / den. Nepředpokládám že by se ten limit hitnul když by se to spouštělo jen při každém mergi a ne commitu
- testuje se jen frontend (takže mockuje Firebase, fakují http API cally), na testování Backendu bude pak samostatná workflow kde se bude generovat ten token

Většina configů z ofic. zdroje: https://github.com/flutter/flutter/tree/master/packages/integration_test#firebase-test-lab
Co se týče setupu, zbývá nastavit secrets do Githubu a udělat 1 změnu v právech v Google Cloud

2022-04-06 06:25 UTC, martin-ladecky requested changes
Chválim za používanie shell skriptov :). Prosím uprav tie new line a budem v nebi :).

2022-04-06 06:25 UTC, martin-ladecky commented on bin/ci_workflow_scripts/env_copy.sh
> +cp ./assets/.env.example ./assets/.env
Viem, že som puntičkár, ale new line na konci súboru prosím :). Aj github kvíka. Ďakujem.

2022-04-06 06:25 UTC, martin-ladecky commented on bin/ci_workflow_scripts/update_gradle.sh
> +sed -i -e '/end remove second/,+1d;' ./android/app/build.gradle
Viem, že som puntičkár, ale new line na konci súboru prosím :). Aj github kvíka. Ďakujem.

2022-04-06 09:09 UTC, mzdm commented on bin/ci_workflow_scripts/env_copy.sh
> +cp ./assets/.env.example ./assets/.env
chápu, done :D

2022-04-08 08:43 UTC, martin-ladecky approved these changes

2022-04-08 11:41 UTC, martin-ladecky approved these changes

2022-04-08 11:41 UTC, merged