LOON-193 Doctor progress indicators - update
cesko-digital/loono pull request #24
Opened 2021-08-30 12:30 UTC by mzdm

https://cesko-digital.atlassian.net/browse/LOON-193

updatnutí těch indikatorů u doktorů

- před
![image](https://user-images.githubusercontent.com/67197047/131339149-959e37f7-4e03-4133-8d96-dac55801d8a1.png)

- po 
![image](https://user-images.githubusercontent.com/67197047/131338784-7d2e6310-c9e0-4d1c-9969-41946af32fbc.png)

2021-08-31 13:16 UTC, mzdm commented
(ještě se přidaj ty tečky mezitím)

2021-09-01 17:07 UTC, ryzizub requested changes
Nějaké drobnosti na úpravu prosím

2021-09-01 17:07 UTC, ryzizub commented on lib/ui/widgets/progress_dots.dart
> +        dots.add(const ProgressDot(style: ProgressDotStyle.done, text: ''));
Prosím neposílej prázdný text jako value, dal bych to optionable. Když nebude text tak prostě ta dot bude prázdná když se něco pošle tak se to zobrazí

2021-09-01 17:07 UTC, ryzizub commented on lib/ui/widgets/progress_dots.dart
> +                ...List.generate(
To už se dá použít přímo jako children a nemusí se použít spread

2021-09-01 17:17 UTC, mzdm commented on lib/ui/widgets/progress_dots.dart
> +                ...List.generate(
nice catch 👍

2021-09-04 15:35 UTC, mzdm commented
ještě jsem vycentroval ty čárky, at je to stejný na obou stranách
![image](https://user-images.githubusercontent.com/67197047/132099980-5ed86714-005b-4b46-ab15-c46ae30dc934.png)

2021-09-09 16:27 UTC, killalad approved these changes
lgtm

2021-09-16 07:51 UTC, ryzizub approved these changes

2021-09-18 10:49 UTC, merged