LOON-237 Logout
cesko-digital/loono pull request #43
Opened 2021-10-26 12:30 UTC by phiviet01

2021-10-30 18:53 UTC, killalad requested changes

2021-10-30 18:53 UTC, killalad commented on lib/ui/screens/logout.dart
> +    _authService.signOut();
mno, tohle je problematicky, je potreba aby se pri logoutu delal kompletni reset vicemene vseho, respektive nejde jen o authentizaci, ale kdyz se clovek odhlasi tak je potreba smazat i local storage, resetovat fcm token aby nechodili pushky a podobne,, hadam ze na to neni task nekde stranou tak bych to udelal v ramci tohoto PR trochu vic poradne

2021-10-30 18:53 UTC, killalad commented on lib/ui/screens/settings/update_profile.dart
> +                          onConfirm: () => AutoRouter.of(context).pushAndPopUntil(
ten logout bych delal pro jistotu tady, aby kdyz failne, treba ze bude potrebovat internet (ikdyz ted zatim tam nic takoveho nemame), tak failne tady

2021-10-30 18:53 UTC, killalad commented on lib/ui/screens/settings/update_profile.dart
> +                            const LogoutRoute(),
@mzdm jak jsme se to nakonec dohodli ohledne toho routingu v ramci authentizace a podobnych veci? bylo by pekny kdybychom ty koncepty meli separovany aby se to nezaclo motat do sebe

2021-10-30 19:18 UTC, mzdm commented on lib/ui/screens/settings/update_profile.dart
> +                            const LogoutRoute(),
tu je ticket https://cesko-digital.atlassian.net/browse/LOON-273
nej bude jaks ukazoval mít separátní routery pro auth a pak nějakej basic
ale to má podle mě smysl udělat až se přemigruje na ten novej onboarding (nebo zároven s tím), protože ten nám zas rozkope spoustu věcí

2021-10-30 20:01 UTC, phiviet01 commented on lib/ui/screens/settings/update_profile.dart
> +                          onConfirm: () => AutoRouter.of(context).pushAndPopUntil(
původně jsem logout chtěl taky provést zde, ale problém je v https://github.com/cesko-digital/loono/blob/b7d8281b0a81964826786b655ad431bb203c30ce/lib/loono.dart#L23
Tenhle stream poslouchá změny u uživatele a pokud je null tak ho to rovnou vykopne na MainScreenRouter. Proto jsem tam přidal podmínku, že ho to vykopne pouze pokud se nenachází na stránce `logout`. Z toho důvodu logout musí proběhnout na stránce LogoutScreen. Jinak jsem nevěděl, jak to vyřešit. Napadá vás něco? @killalad @mzdm

2021-10-30 20:03 UTC, phiviet01 commented on lib/ui/screens/logout.dart
> +    _authService.signOut();
Aha, takže pročistit local storage, reset fcm token. Ještě něco?

2021-10-31 07:35 UTC, mzdm commented on lib/ui/screens/settings/update_profile.dart
> +                          onConfirm: () => AutoRouter.of(context).pushAndPopUntil(
asi bych tam dal TODO s linkem na to issue viz koment dole
s tím se asi teď nic moc nedá dělat

2021-11-01 07:45 UTC, killalad commented on lib/ui/screens/logout.dart
> +    _authService.signOut();
asi zatim jen takhle, az budem mit db sifrovanou pres klic tak bude potreba mazat i ten klic a znovu inicailizovat DB, ale tim se ted netrapme

2021-11-01 07:46 UTC, killalad commented on lib/ui/screens/settings/update_profile.dart
> +                          onConfirm: () => AutoRouter.of(context).pushAndPopUntil(
okok, `TODO` je za me idealni, ono se to pravdepodobne vyresi s temi separatnimi routery

2021-11-01 07:46 UTC, killalad commented on lib/ui/screens/settings/update_profile.dart
> +                            const LogoutRoute(),
jojo tak super, ja jen aby to nekde nezapadlo

2021-11-01 07:47 UTC, killalad commented
jinak prosim jeste konflikty, krom toho cisteni:)

2021-11-02 22:02 UTC, phiviet01 commented
@killalad updatnuto.

2021-11-04 17:23 UTC, killalad approved these changes
lgtm, jen prosim bacha na ty git commity, koukal jsem ze tam mas nejaky force tak to neni nikdy idealni :D

2021-11-04 17:23 UTC, merged

2021-11-04 22:34 UTC, phiviet01 commented
@killalad Jsem squashnul dva commity k sobě a taky rebasnul k masteru, tak proto bylo potřeba to forcenout :D. A navíc to byl `--force-with-lease`, takže v podstatě safe force :D.