feat: upload and cache user photo
cesko-digital/loono pull request #48
Opened 2021-11-21 14:08 UTC by mzdm

https://cesko-digital.atlassian.net/browse/LOON-320

2021-11-24 22:04 UTC, mzdm commented
@killalad ready:)

2021-11-29 12:30 UTC, killalad commented on lib/services/db/database.dart
> +  int get schemaVersion => 2;
chceme uz zacit delat migrace? osobne bych se primlouval za to ze dokud appka neni v appstorech tak testeri delaji fresh install

2021-11-29 12:37 UTC, killalad requested changes

2021-11-29 12:37 UTC, killalad commented on lib/services/firebase_storage_service.dart
> +  // TODO: Error handling
na ten error handling jsou nejake karticky nebo tak? aby si pak ostatni nemysleli ze to je udelano uplne

2021-11-29 12:37 UTC, killalad commented on lib/utils/registry.dart
> +  registry.registerLazySingleton<DefaultCacheManager>(() => DefaultCacheManager());
mame v planu ho nejak do budoucna pouzivat?

2021-11-29 12:37 UTC, killalad commented on lib/utils/registry.dart
> +  registry.registerLazySingleton<DefaultCacheManager>(() => DefaultCacheManager());
zatim je jen v logoutu

2021-11-29 13:06 UTC, mzdm commented on lib/services/db/database.dart
> +  int get schemaVersion => 2;
to nevím jestli dělaj fresh install, bylo by asi dobré jim to říct

2021-11-29 13:07 UTC, mzdm commented on lib/utils/registry.dart
> +  registry.registerLazySingleton<DefaultCacheManager>(() => DefaultCacheManager());
může se odhlásit víckrát

2021-11-29 13:30 UTC, mzdm commented on lib/services/firebase_storage_service.dart
> +  // TODO: Error handling
založil jsem 👍

2021-11-29 17:16 UTC, killalad commented on lib/utils/registry.dart
> +  registry.registerLazySingleton<DefaultCacheManager>(() => DefaultCacheManager());
pockej jak tohle myslis? asi trochu nechapu jde mi o to ze ten DefaultCacheManager nepouzivame

2021-11-29 17:19 UTC, killalad commented on lib/services/db/database.dart
> +  int get schemaVersion => 2;
hele tak bych ty migrace zrusil a rekl testerum at delaji fresh install

2021-11-29 18:25 UTC, mzdm commented on lib/utils/registry.dart
> +  registry.registerLazySingleton<DefaultCacheManager>(() => DefaultCacheManager());
jaj, tu se používá https://github.com/cesko-digital/loono/blob/543980004e9389c8fc16c5e8fb66495229838b84/lib/ui/screens/logout.dart#L37 :D

2021-12-01 21:55 UTC, killalad approved these changes
lgtm

2021-12-01 21:55 UTC, merged