feat: storing simple healthcare providers data
cesko-digital/loono pull request #51
Opened 2021-11-26 10:45 UTC by mzdm

2021-12-08 21:05 UTC, killalad requested changes

2021-12-08 21:05 UTC, killalad commented on lib/ui/widgets/find_doctor/map_preview.dart
> +  Set<Marker> markers = Set();
lint issue:)

2021-12-08 21:05 UTC, killalad commented on lib/ui/widgets/find_doctor/map_preview.dart
> +    mapStateService = context.read<MapStateService>();
nepouzijem tu `mapStateService` i na ty markery? zbavime se tak jednoduse toho statefull widgetu

2021-12-08 21:05 UTC, killalad commented on lib/utils/map_utils.dart
> +  final data = await img.toByteData(format: ImageByteFormat.png);
fakt cool, neznal jsem

2021-12-11 13:12 UTC, mzdm commented on lib/ui/widgets/find_doctor/map_preview.dart
> +    mapStateService = context.read<MapStateService>();
ten `stateful` musí být kvůli inicializování _cluster manageru_, ale ty markery jsem tam přesunul 👍

2021-12-11 13:12 UTC, mzdm commented on lib/repositories/healthcare_repository.dart
> +      serverLatestUpdateResponse = await _api.getProvidersApi().getProvidersLastupdate();
good point, nastavil jsem check na každých 21 dní

2021-12-12 13:27 UTC, killalad commented on lib/ui/widgets/find_doctor/map_preview.dart
> +    mapStateService = context.read<MapStateService>();
noo a ten cluster manager nemuze byt na `mapStateService`?

2021-12-12 13:29 UTC, killalad requested changes
jeste ten posledni thread:)

2021-12-12 14:17 UTC, mzdm commented on lib/ui/widgets/find_doctor/map_preview.dart
> +    mapStateService = context.read<MapStateService>();
aha takto
done 🙂

2021-12-14 12:48 UTC, killalad approved these changes
lgtm

2021-12-14 12:48 UTC, merged