feat: facebook sign in
cesko-digital/loono pull request #52
Opened 2021-11-28 20:53 UTC by MartinMacek

1. Propojeno s Loono FB appkou.
2. Přidány tlačítka pro přihlášení přes FB.
3. Ověření existujícího emailu/účtu. Viz. existující řešení google a apple přihlášení.
4. Kvůli balíčku `flutter_facebook_auth` navýšena verze kotlinu na 1.6.0 po dohodě s @martin-ladecky 

Future tasks:

- Před releasem vytvořit nový android Relese Hash Key [viz bod 6 zde](https://developers.facebook.com/docs/facebook-login/android)
- Přepnout FB applikaci z režimu Development do Live
- Aktuální přihlášení přes socky prozatím nenačítá uživatelské data z firebase do profilu

2021-11-29 12:49 UTC, killalad requested changes

2021-11-29 12:49 UTC, killalad commented on lib/services/auth/auth_service.dart
> +      userCredential = await _auth.signInWithCredential(facebookAuthCredential);
kdyz tady delas tu novou promnenou, tak vzhledem k tomu ze `signInWithCredential` vraci  UserCredential tak muzes ten return z 152 dat rovnou sem bez null checku, obecne bych tam zbytecne nedaval moznost null kdyz tam neni treba, je to pak citelnejsi:)

2021-11-30 11:08 UTC, MartinMacek commented on lib/services/auth/auth_service.dart
> +      userCredential = await _auth.signInWithCredential(facebookAuthCredential);
Good point. Diky. Opraveno

2021-12-01 21:56 UTC, killalad approved these changes
lgtm!

2021-12-01 21:56 UTC, merged