Success message bottom to top loon 397
cesko-digital/loono pull request #57
Opened 2021-12-17 09:02 UTC by MiroslavPeterka1

Dobrý den,

nakonec to pro mě popravdě nebyla taková prkotina jak jsem čekal. Ta zpráva byla realizovaná pomoci snackbaru z scafold -> messangeru, která využívá toho, že i po změně screenu zpráva zůstává uživateli viditelná. 
Způsobu jak to udělat jsem viděl víc a tak popíšu jak jsem došel k tomu řešení:
1) Snack bar udělat transparentní a vytáhnout ho až nahoru na požadované umístění -> Zamítl jsem, protože by snackbar překryl tlačítka a nešli by používat.
2) Poslat si přes router atribut a ten zobrazit v požadovaném místě -> Překrytí je podle zadání v appBaru + by jsem musel použít stuck a celé by to bylo nepřeužitelné. Zamítnuto
3) Udělat HOC widget, který by obalil scaffold -> body. To jsem zvažoval dlouho, ale nakonec zamítnul.
4) Prostudovat jak funguje klasicky snack bar -> zdědit třídu a přepsat a následně použit přepsanou -> to mi přišlo jako kladivo na komára a vlastně by jsem psal vlastní knihovnu... 

Nakonec jsem teda našel knihovnu, která ve své podstatě dělá to samé, co snackbar (kupa možností jak změnit visuál + chování), jen má limitaci, že nezůstane vidět i po tom, co se přejde na jiný screen. Proto jsem ještě upravil routování.

Nevím jestli se pull request takto rozepisuje ....pardon ...můj první.

P.S.: Omlouvám se za gramatiku ... vím ... je to ostuda ...a ne nezlepší se to :-).

P.S..2: Auto_route jsme viděl poprvé a pořád nevím, jestli ji mám milovat, nebo nenávidět :-D.

2021-12-19 18:04 UTC, mzdm commented on lib/ui/screens/settings/photo_cropped_result.dart
> +                        ));
```suggestion
                        AutoRouter.of(context).pushAndPopUntil(
                          EditPhotoRoute(
                            imageBytes: widget.imageBytes,
                            successMessage: context.l10n.photo_changed_success,
                          ),
                          predicate: (route) => route.settings.name == UpdateProfileRoute.name,
                        );
```

oficiálně SnackBar nejde nativně dát nahoru, protože Flutter followuje Material Design, který to "zakazuje" mít nahoře 👍


tady jen trošku problém, že po uložení se tahle route přidá do route stacku, tím pádem se může vrátit zpátky na tu confirmační screenu s fotkou (takže loop), ale správně by kliknutím na back button vrátit do hlavní editační menu screeny (tak jak to bylo předtím)

teď:
UpdateProfileRoute -> EditPhotoRoute -> CameraPhotoTakenRoute -> PhotoCroppedResultRoute -> EditPhotoRoute

předtím:
UpdateProfileRoute -> EditPhotoRoute -> CameraPhotoTakenRoute -> PhotoCroppedResultRoute 
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀^----------------------------------------------------|

2021-12-20 16:06 UTC, mzdm commented on lib/ui/screens/settings/photo_cropped_result.dart
> +                        ));
takže bych nechal toto, jen s tím přidaným argumentem `successMessage`:
```dart
                        AutoRouter.of(context).pushAndPopUntil(
                          EditPhotoRoute(
                            imageBytes: widget.imageBytes,
                            successMessage: context.l10n.photo_changed_success,
                          ),
                          predicate: (route) => route.settings.name == UpdateProfileRoute.name,
                        );
```

2021-12-22 09:00 UTC, MiroslavPeterka1 commented on lib/ui/screens/settings/photo_cropped_result.dart
> +                        ));
Super, díky! ;-)
Neznám proces pull requestu, tak se omlouvám za blbou otázku... Je k tomuto požadavku ještě něco třeba ode mě? Předpokládám, že vy úpravu do kódu udělate na úrovni requestu a při případném mergy by již vaše změny měl být refelektované?

2021-12-22 18:53 UTC, mzdm commented on lib/ui/screens/settings/photo_cropped_result.dart
> +                        ));
já práva nemám, takže editovat nic nemůžu, ale tu to funguje tak, že ten kdo submitnul ten Pull Request, tak i ten ty suggested/requested změny udělá, a pak je pushne sem do PR :)

2021-12-23 15:15 UTC, killalad commented on lib/ui/screens/settings/photo_cropped_result.dart
> +                        ));
jojo jak pise Matej, autor PRka dela pripadne upravy podle toho jak se domluvime v ramci code review

2021-12-23 15:21 UTC, killalad requested changes
jeste nejake drobnosti, ale moc diky za PRko!

2021-12-23 15:21 UTC, killalad commented on assets/.env.example
> -API_URL=https://loono.ceskodigital.net/
prosim tenhle file urcite nemazat a vratit :smile:

2021-12-23 15:21 UTC, killalad commented on lib/ui/screens/settings/photo_cropped_result.dart
> +                        context.pushRoute(EditPhotoRoute(
v tom commentu pises ze ten `Flushbar` nezustava pri zmene screeny, nemohl bys teda ty flushbary dat az po tomhle `pushRoute` a pak by se ti tam zobrazili?

2021-12-25 03:53 UTC, MiroslavPeterka1 commented on lib/ui/screens/settings/photo_cropped_result.dart
> +                        context.pushRoute(EditPhotoRoute(
Zapracováno, hodil jsme to sem a funguje ;-)

2021-12-25 03:53 UTC, MiroslavPeterka1 commented on lib/ui/screens/settings/photo_cropped_result.dart
> +                        ));
Vrátil jsem původní routování viz řešení od @killalad. Díky!

2021-12-29 14:20 UTC, killalad commented on assets/.env.example
> -API_URL=https://loono.ceskodigital.net/
prosim toto:)

2021-12-29 19:37 UTC, MiroslavPeterka1 commented on assets/.env.example
> -API_URL=https://loono.ceskodigital.net/
Jsem pako, pardon ;-)

2021-12-30 10:25 UTC, killalad approved these changes
lgtm

2021-12-30 10:25 UTC, merged